import Head from 'next/head'
import Image from 'next/image'
import Menu from '../components/Menu'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
import {useRouter} from 'next/router'
import api from '../pages/api/api'

export default function Livro() {
  const [formulario , setFormulario] = useState ({})
  function handleInputChange(e) {
    const {id, value} = e.target;
    setFormulario({ ...formulario, [id]: value });
  }
  console.log(formulario);
  const router = useRouter();
  async function handleSubmit(e) {
    e.preventDefault()
    const data = {
      titulo: formulario.titulo,
      autorId: formulario.autor,
      editora: formulario.editora,
      data_publicacao: formulario.data,
      preco: formulario.preco,
    }
    console.log(data)
    const response = await api.post('/livros', data)
    console.log(response);
    router.push('/livros')
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>ACN Library</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className={styles.main}>
        <div className={styles.livro}>
        <div className={styles.img4}>
          <img className={styles.img4}
        src="/images/livro.jpg"
        height={700}
        width={680}
        alt="Imagem Ilustrativa"
      />
        </div>

          <form onSubmit={handleSubmit} className={styles.todo} action="/send-data-here" method="post">
            
          <div className={styles.title}>
            Cadastre um novo Livro
          </div>
            
          <div className={styles.nome}>
            <label for="titulo">Titulo:</label><br/>
            <input className={styles.caixa} type="text" placeholder="Digite o nome do livro" id="titulo" onChange={handleInputChange} value = {formulario.titulo || ''} />
          </div>
    
          <div className={styles.autor}>
            <label for="autor">Autor:</label> <br/>
            <input className={styles.caixa} type="text" placeholder="Digite o autor do livro"id="autor" onChange={handleInputChange} value = {formulario.autor || ''} />
          </div>

          <div className={styles.editora}>
            <label for="editora">Editora:</label> <br/>
            <input className={styles.caixa} type="text" placeholder="Digite a editora do livro" id="editora" onChange={handleInputChange} value = {formulario.editora || ''} />
          </div>
    
          <div className={styles.publicacao}>
            <label for="date">Data de Publicação:</label> <br/>
            <input className={styles.caixa} type="date" id="data" onChange={handleInputChange} value = {formulario.data || ''}/>
          </div>

          <div className={styles.preco}>
            <label for="preco">Preço:</label> <br/>
            <input className={styles.caixa} type="number" placeholder="Digite o valor do livro" id="preco" onChange={handleInputChange} value = {formulario.preco || ''} />
          </div>
    
          <div className={styles.enviar}>
            <button className={styles.botao} type="submit">Enviar</button>
          </div>
      </form>
          </div>
      </main>

      <footer className={styles.footer}>
          Todos os direitos reservados
      </footer>
    </div>
  )
}