import api from './api/api'
import Menu from '../components/Menu.js'
import ListaAutor from '../components/ListaAutor.js'
import Head from 'next/head'

export async function getServerSideProps() {
  const response = await api.get ('/autores')
    console.log(response.data);
  const autor = response.data;
  return {
    props: {
      autor
    }
  }
}

export default function autor_l({autor}) {
  return (
    <div>
      <Head>
        <title>ACN Library</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <div>
      {
        autor.map(listage => {
          return(
            <div key={listage.id}>
              <ListaAutor nome={listage.nome} sobrenome={listage.sobrenome} data_nascimento={listage.data_nascimento} id={listage.id}/>
            </div>
          )
        })
      }
    </div>
      <footer class="footer1">
          Todos os direitos reservados
      </footer>
    </div>
  )
}