import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../components/Menu.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ACN Library</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Menu/>

      <main className={styles.main}>
        <div className={styles.meio}>
          <Image className={styles.img2}
        src="/images/principal.jpg"
        height={800}
        width={1500}
        alt="Imagem Ilustrativa"
      />
        </div>
      </main>

      <footer className={styles.footer}>
          Todos os direitos reservados
      </footer>
    </div>
  )
}
