import Menu from '../components/Menu.js'
import ListaLivro from '../components/ListaLivro.js'
import api from './api/api'
import Head from 'next/head'

export async function getServerSideProps() {
  const response = await api.get ('/livros')
    console.log(response.data);
  const livro = response.data;
  return {
    props: {
      livro
    }
  }
}

export default function livro_l({livro}) {
  return (
    <div>
      <Head>
        <title>ACN Library</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <div>
      {
        livro.map(listagem => {
          return(
            <div key={listagem.id}>
              <ListaLivro titulo={listagem.titulo} editora={listagem.editora} data_publicacao={listagem.data_publicacao} preco={listagem.preco} id={listagem.id}/>
            </div>
          )
        })
      }
    </div>
      <footer class="footer">
          Todos os direitos reservados
      </footer>
    </div>
  )
}